/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        role: {
          government: '#3b82f6',
          university: '#6366f1',
          industry: '#a855f7',
          urgent: '#ef4444',
          review: '#f59e0b',
        },
        surface: {
          dim: '#0b0f19',
          DEFAULT: '#0b0f19',
          container: '#111827',
          'container-low': '#0d1322',
          'container-lowest': '#070b14',
          'container-high': '#1e293b',
          'container-highest': '#1e293b',
          bright: '#1e293b',
          variant: '#1e293b',
        }
      },
      spacing: {
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'container-max': '80rem',
        'space-1': '0.25rem',
        'space-2': '0.5rem',
        'space-3': '0.75rem',
        'space-4': '1rem',
        'space-5': '1.25rem',
        'space-6': '1.5rem',
        'space-8': '2rem',
        'space-10': '2.5rem',
        'space-12': '3rem',
        'space-16': '4rem',
        'space-20': '5rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        display: ['Outfit', '"Plus Jakarta Sans"', 'sans-serif'],
        'data-mono': ['"JetBrains Mono"', 'monospace'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'headline-sm': ['Outfit', 'sans-serif'],
        'headline-xl': ['Outfit', 'sans-serif'],
        'display-hero': ['Outfit', 'sans-serif'],
        'body-default': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-medium': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lead': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-button': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-caption': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 28s linear infinite',
      },
    },
  },
  plugins: [],
}
